datasets:
  dcpgs:
    resource-path: data/dcpgs/
    checkin-files:
      gowalla: gowalla/loc-gowalla_totalCheckins.txt
      brightkite: brightkite/loc-brightkite_totalCheckins.txt
    edge-files:
      gowalla: gowalla/loc-gowalla_edges.txt
      brightkite: brightkite/loc-brightkite_edges.txt
  topk:
    base-path: data/topk/
    eid2keyword: eid2keyword.txt
    eid2coor: eid2coor.txt
    relation2id: relation2id.txt
    train2id: train2id.txt
    entity: Entity.txt
  pa:
    base-path: data/pa/
    target-path: data/pa-geojson/
  kdv:
    data-path: data/kdv/
  std:
    rtree-path: data/std/rtreeSkyline.txt
    objs-path: data/std/objsSkyline.txt
    ifile-path: data/std/iFileSkyline.txt
